### PR TITLE
feat: add toasts to signify errors

### LINKED ISSUE #10: UI: Add toasts to signify errors
We have toasts now. We can make a pop-up toast for errors.

@rekols @ChungZH

### PR DESCRIPTION
**Pull request by ChungZH**
image

Close #10

### CODE REVIEW

**Comment by ChungZH** [comment]
close #10

**Comment by itsvic-dev** [comment]
@ChungZH have you found a way to push the toast down?

**Comment by zirnc** [comment]
> @ChungZH have you found a way to push the toast down?

No, I haven't. I didn't work on it.

**Comment by itsvic-dev** [comment]
@ChungZH @rekols Check the toasts now, let me know what you think.

**Comment by reionwong** [comment]
You need to add a translation to the error message and use the tr function. @ChungZH

**Comment by itsvic-dev** [comment]
Ah, right. I'll deal with it.

**Pull request merged**
